// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZKfqX62Ma651W7qIp5UFgz2uSonJUIpY',
    appId: '1:848836436172:web:c14cdb4fafef2b39e3e269',
    messagingSenderId: '848836436172',
    projectId: 'cinetec-2011d',
    authDomain: 'cinetec-2011d.firebaseapp.com',
    storageBucket: 'cinetec-2011d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiY9rR8cb6cZNFpp3fgwKcgDAReLod1yY',
    appId: '1:848836436172:android:9746b4ac7efb36bde3e269',
    messagingSenderId: '848836436172',
    projectId: 'cinetec-2011d',
    storageBucket: 'cinetec-2011d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALS7xj6w_ZJYsAo0miYKqD8-7Ku3YMoq4',
    appId: '1:848836436172:ios:ea9e254657aa1c75e3e269',
    messagingSenderId: '848836436172',
    projectId: 'cinetec-2011d',
    storageBucket: 'cinetec-2011d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALS7xj6w_ZJYsAo0miYKqD8-7Ku3YMoq4',
    appId: '1:848836436172:ios:ea9e254657aa1c75e3e269',
    messagingSenderId: '848836436172',
    projectId: 'cinetec-2011d',
    storageBucket: 'cinetec-2011d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZKfqX62Ma651W7qIp5UFgz2uSonJUIpY',
    appId: '1:848836436172:web:6c790274de25fe6de3e269',
    messagingSenderId: '848836436172',
    projectId: 'cinetec-2011d',
    authDomain: 'cinetec-2011d.firebaseapp.com',
    storageBucket: 'cinetec-2011d.firebasestorage.app',
  );

}